package nchu.wuxi.xmeet.entity;

import java.io.Serializable;

public class TApplyResponse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_response.apply_phone
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    private String applyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_response.op_phone
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    private String opPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_response.code
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_response.enterprise_id
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_response.apply_phone
     *
     * @return the value of t_apply_response.apply_phone
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public String getApplyPhone() {
        return applyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_response.apply_phone
     *
     * @param applyPhone the value for t_apply_response.apply_phone
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public void setApplyPhone(String applyPhone) {
        this.applyPhone = applyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_response.op_phone
     *
     * @return the value of t_apply_response.op_phone
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public String getOpPhone() {
        return opPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_response.op_phone
     *
     * @param opPhone the value for t_apply_response.op_phone
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public void setOpPhone(String opPhone) {
        this.opPhone = opPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_response.code
     *
     * @return the value of t_apply_response.code
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_response.code
     *
     * @param code the value for t_apply_response.code
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_response.enterprise_id
     *
     * @return the value of t_apply_response.enterprise_id
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_response.enterprise_id
     *
     * @param enterpriseId the value for t_apply_response.enterprise_id
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }
}