package nchu.wuxi.xmeet.entity;

import java.util.ArrayList;
import java.util.List;

public class TApplyResponseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public TApplyResponseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApplyPhoneIsNull() {
            addCriterion("apply_phone is null");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneIsNotNull() {
            addCriterion("apply_phone is not null");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneEqualTo(String value) {
            addCriterion("apply_phone =", value, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneNotEqualTo(String value) {
            addCriterion("apply_phone <>", value, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneGreaterThan(String value) {
            addCriterion("apply_phone >", value, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("apply_phone >=", value, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneLessThan(String value) {
            addCriterion("apply_phone <", value, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneLessThanOrEqualTo(String value) {
            addCriterion("apply_phone <=", value, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneLike(String value) {
            addCriterion("apply_phone like", value, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneNotLike(String value) {
            addCriterion("apply_phone not like", value, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneIn(List<String> values) {
            addCriterion("apply_phone in", values, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneNotIn(List<String> values) {
            addCriterion("apply_phone not in", values, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneBetween(String value1, String value2) {
            addCriterion("apply_phone between", value1, value2, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andApplyPhoneNotBetween(String value1, String value2) {
            addCriterion("apply_phone not between", value1, value2, "applyPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneIsNull() {
            addCriterion("op_phone is null");
            return (Criteria) this;
        }

        public Criteria andOpPhoneIsNotNull() {
            addCriterion("op_phone is not null");
            return (Criteria) this;
        }

        public Criteria andOpPhoneEqualTo(String value) {
            addCriterion("op_phone =", value, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneNotEqualTo(String value) {
            addCriterion("op_phone <>", value, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneGreaterThan(String value) {
            addCriterion("op_phone >", value, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("op_phone >=", value, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneLessThan(String value) {
            addCriterion("op_phone <", value, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneLessThanOrEqualTo(String value) {
            addCriterion("op_phone <=", value, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneLike(String value) {
            addCriterion("op_phone like", value, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneNotLike(String value) {
            addCriterion("op_phone not like", value, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneIn(List<String> values) {
            addCriterion("op_phone in", values, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneNotIn(List<String> values) {
            addCriterion("op_phone not in", values, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneBetween(String value1, String value2) {
            addCriterion("op_phone between", value1, value2, "opPhone");
            return (Criteria) this;
        }

        public Criteria andOpPhoneNotBetween(String value1, String value2) {
            addCriterion("op_phone not between", value1, value2, "opPhone");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(Integer value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(Integer value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(Integer value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(Integer value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(Integer value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<Integer> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<Integer> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(Integer value1, Integer value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNull() {
            addCriterion("enterprise_id is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNotNull() {
            addCriterion("enterprise_id is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdEqualTo(Integer value) {
            addCriterion("enterprise_id =", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotEqualTo(Integer value) {
            addCriterion("enterprise_id <>", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThan(Integer value) {
            addCriterion("enterprise_id >", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("enterprise_id >=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThan(Integer value) {
            addCriterion("enterprise_id <", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThanOrEqualTo(Integer value) {
            addCriterion("enterprise_id <=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIn(List<Integer> values) {
            addCriterion("enterprise_id in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotIn(List<Integer> values) {
            addCriterion("enterprise_id not in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdBetween(Integer value1, Integer value2) {
            addCriterion("enterprise_id between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("enterprise_id not between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_apply_response
     *
     * @mbg.generated do_not_delete_during_merge Tue May 05 16:19:11 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_apply_response
     *
     * @mbg.generated Tue May 05 16:19:11 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}