package nchu.wuxi.xmeet.entity;

import java.io.Serializable;

public class TChatRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_record.from_id
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    private String fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_record.to_id
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    private String toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_record.msg
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_record.type
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_record.mills
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    private Long mills;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_chat_record
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_record.from_id
     *
     * @return the value of t_chat_record.from_id
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public String getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_record.from_id
     *
     * @param fromId the value for t_chat_record.from_id
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_record.to_id
     *
     * @return the value of t_chat_record.to_id
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public String getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_record.to_id
     *
     * @param toId the value for t_chat_record.to_id
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public void setToId(String toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_record.msg
     *
     * @return the value of t_chat_record.msg
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_record.msg
     *
     * @param msg the value for t_chat_record.msg
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_record.type
     *
     * @return the value of t_chat_record.type
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_record.type
     *
     * @param type the value for t_chat_record.type
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_record.mills
     *
     * @return the value of t_chat_record.mills
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public Long getMills() {
        return mills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_record.mills
     *
     * @param mills the value for t_chat_record.mills
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    public void setMills(Long mills) {
        this.mills = mills;
    }
}