package nchu.wuxi.xmeet.entity;

import java.io.Serializable;

public class TCustomer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.phone
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.password
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.nick_name
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.enterprise_id
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.live_rome_id
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private Integer liveRomeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.state
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.post
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.dept_name
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.head_url
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private String headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.enterpriseName
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private String enterprisename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.manage_enterpriseId
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private Integer manageEnterpriseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.phone
     *
     * @return the value of t_customer.phone
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.phone
     *
     * @param phone the value for t_customer.phone
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.password
     *
     * @return the value of t_customer.password
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.password
     *
     * @param password the value for t_customer.password
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.nick_name
     *
     * @return the value of t_customer.nick_name
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.nick_name
     *
     * @param nickName the value for t_customer.nick_name
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.enterprise_id
     *
     * @return the value of t_customer.enterprise_id
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.enterprise_id
     *
     * @param enterpriseId the value for t_customer.enterprise_id
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.live_rome_id
     *
     * @return the value of t_customer.live_rome_id
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public Integer getLiveRomeId() {
        return liveRomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.live_rome_id
     *
     * @param liveRomeId the value for t_customer.live_rome_id
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setLiveRomeId(Integer liveRomeId) {
        this.liveRomeId = liveRomeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.state
     *
     * @return the value of t_customer.state
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.state
     *
     * @param state the value for t_customer.state
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.post
     *
     * @return the value of t_customer.post
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.post
     *
     * @param post the value for t_customer.post
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setPost(String post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.dept_name
     *
     * @return the value of t_customer.dept_name
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.dept_name
     *
     * @param deptName the value for t_customer.dept_name
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.head_url
     *
     * @return the value of t_customer.head_url
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.head_url
     *
     * @param headUrl the value for t_customer.head_url
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.enterpriseName
     *
     * @return the value of t_customer.enterpriseName
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public String getEnterprisename() {
        return enterprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.enterpriseName
     *
     * @param enterprisename the value for t_customer.enterpriseName
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setEnterprisename(String enterprisename) {
        this.enterprisename = enterprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.manage_enterpriseId
     *
     * @return the value of t_customer.manage_enterpriseId
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public Integer getManageEnterpriseid() {
        return manageEnterpriseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.manage_enterpriseId
     *
     * @param manageEnterpriseid the value for t_customer.manage_enterpriseId
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    public void setManageEnterpriseid(Integer manageEnterpriseid) {
        this.manageEnterpriseid = manageEnterpriseid;
    }
}