package nchu.wuxi.xmeet.entity;

import java.io.Serializable;

public class TLiveRome implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.rome_id
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private Integer romeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.rome_name
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private String romeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.owner_phone
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private String ownerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.enterprise_id
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.content
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.label
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.pic_url
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.state
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.owner_name
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private String ownerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_live_rome.status
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_live_rome
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.rome_id
     *
     * @return the value of t_live_rome.rome_id
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public Integer getRomeId() {
        return romeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.rome_id
     *
     * @param romeId the value for t_live_rome.rome_id
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setRomeId(Integer romeId) {
        this.romeId = romeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.rome_name
     *
     * @return the value of t_live_rome.rome_name
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public String getRomeName() {
        return romeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.rome_name
     *
     * @param romeName the value for t_live_rome.rome_name
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setRomeName(String romeName) {
        this.romeName = romeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.owner_phone
     *
     * @return the value of t_live_rome.owner_phone
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public String getOwnerPhone() {
        return ownerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.owner_phone
     *
     * @param ownerPhone the value for t_live_rome.owner_phone
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setOwnerPhone(String ownerPhone) {
        this.ownerPhone = ownerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.enterprise_id
     *
     * @return the value of t_live_rome.enterprise_id
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.enterprise_id
     *
     * @param enterpriseId the value for t_live_rome.enterprise_id
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.content
     *
     * @return the value of t_live_rome.content
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.content
     *
     * @param content the value for t_live_rome.content
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.label
     *
     * @return the value of t_live_rome.label
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.label
     *
     * @param label the value for t_live_rome.label
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.pic_url
     *
     * @return the value of t_live_rome.pic_url
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.pic_url
     *
     * @param picUrl the value for t_live_rome.pic_url
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.state
     *
     * @return the value of t_live_rome.state
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.state
     *
     * @param state the value for t_live_rome.state
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.owner_name
     *
     * @return the value of t_live_rome.owner_name
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.owner_name
     *
     * @param ownerName the value for t_live_rome.owner_name
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_live_rome.status
     *
     * @return the value of t_live_rome.status
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_live_rome.status
     *
     * @param status the value for t_live_rome.status
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }
}