package nchu.wuxi.xmeet.mapper;

import java.util.List;
import nchu.wuxi.xmeet.entity.TChatRecord;
import nchu.wuxi.xmeet.entity.TChatRecordExample;
import org.apache.ibatis.annotations.Param;

public interface TChatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_record
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    long countByExample(TChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_record
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    int deleteByExample(TChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_record
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    int insert(TChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_record
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    int insertSelective(TChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_record
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    List<TChatRecord> selectByExample(TChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_record
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") TChatRecord record, @Param("example") TChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_record
     *
     * @mbg.generated Mon May 04 07:21:54 CST 2020
     */
    int updateByExample(@Param("record") TChatRecord record, @Param("example") TChatRecordExample example);
}