package nchu.wuxi.xmeet.mapper;

import java.util.List;
import nchu.wuxi.xmeet.entity.TCustomer;
import nchu.wuxi.xmeet.entity.TCustomerExample;
import org.apache.ibatis.annotations.Param;

public interface TCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    long countByExample(TCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    int deleteByExample(TCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    int insert(TCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    int insertSelective(TCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    List<TCustomer> selectByExample(TCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") TCustomer record, @Param("example") TCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed May 06 09:27:42 CST 2020
     */
    int updateByExample(@Param("record") TCustomer record, @Param("example") TCustomerExample example);

    int updateHeadUrl(@Param("phone") String phone, @Param("headUrl") String headUrl);

    int updateManageEnterprise(@Param("phone") String phone,@Param("enterpriseId") int enterpriseId);

    int joinEnterprise(@Param("phone") String phone,@Param("enterpriseId") int enterpriseId);

    void updateName(@Param("phone") String phone,@Param("name") String name);
}