package nchu.wuxi.xmeet.mapper;

import java.util.List;
import nchu.wuxi.xmeet.entity.TEnterpriseManager;
import nchu.wuxi.xmeet.entity.TEnterpriseManagerExample;
import org.apache.ibatis.annotations.Param;

public interface TEnterpriseManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_manager
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    long countByExample(TEnterpriseManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_manager
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int deleteByExample(TEnterpriseManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_manager
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int insert(TEnterpriseManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_manager
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int insertSelective(TEnterpriseManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_manager
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    List<TEnterpriseManager> selectByExample(TEnterpriseManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_manager
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") TEnterpriseManager record, @Param("example") TEnterpriseManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_manager
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int updateByExample(@Param("record") TEnterpriseManager record, @Param("example") TEnterpriseManagerExample example);
}