package nchu.wuxi.xmeet.mapper;

import java.util.List;
import nchu.wuxi.xmeet.entity.TEnterpriseJoinApply;
import nchu.wuxi.xmeet.entity.TEnterpriseJoinApplyExample;
import org.apache.ibatis.annotations.Param;

public interface TEnterpriseJoinApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_join_apply
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    long countByExample(TEnterpriseJoinApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_join_apply
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int deleteByExample(TEnterpriseJoinApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_join_apply
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int insert(TEnterpriseJoinApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_join_apply
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int insertSelective(TEnterpriseJoinApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_join_apply
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    List<TEnterpriseJoinApply> selectByExample(TEnterpriseJoinApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_join_apply
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") TEnterpriseJoinApply record, @Param("example") TEnterpriseJoinApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise_join_apply
     *
     * @mbg.generated Fri Apr 24 11:23:46 CST 2020
     */
    int updateByExample(@Param("record") TEnterpriseJoinApply record, @Param("example") TEnterpriseJoinApplyExample example);

    int processEnterpriseApply(@Param("enterpriseId") int enterpriseId, @Param("phone") String phone,
                               @Param("code") int code);

    List<TEnterpriseJoinApply> selestByManagerId(@Param("phone") String phone);
}