package nchu.wuxi.xmeet.mapper;

import java.util.List;
import nchu.wuxi.xmeet.entity.TLiveRome;
import nchu.wuxi.xmeet.entity.TLiveRomeExample;
import org.apache.ibatis.annotations.Param;

public interface TLiveRomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_live_rome
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    long countByExample(TLiveRomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_live_rome
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    int deleteByExample(TLiveRomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_live_rome
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    int insert(TLiveRome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_live_rome
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    int insertSelective(TLiveRome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_live_rome
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    List<TLiveRome> selectByExample(TLiveRomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_live_rome
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") TLiveRome record, @Param("example") TLiveRomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_live_rome
     *
     * @mbg.generated Mon Apr 20 16:24:33 CST 2020
     */
    int updateByExample(@Param("record") TLiveRome record, @Param("example") TLiveRomeExample example);

    int updataStatusById(@Param("roomId") int roomId,@Param("status") String status);

    void updateNotice(@Param("roomId") int roomId,@Param("msg") String msg);

    void updatePageUrl(@Param("roomId") int roomId,@Param("fullName") String fullName);
}